// Package envfiles generates the replacement env-bootstrap content that
// used to come from the omarchy/omarchy-settings packages
// (/etc/profile.d/omarchy.sh, /usr/share/uwsm/env.d/10-omarchy), now owned
// by the user instead. Every function here is a pure string transform so it
// can be golden-file tested without touching a filesystem.
package envfiles

import (
	"fmt"
	"strings"
)

// UWSMEnvFile generates ~/.config/uwsm/env.d/10-own-omarchy: the
// replacement for the package-owned /usr/share/uwsm/env.d/10-omarchy, now
// pointing OMARCHY_PATH at the vendored checkout instead of /usr/share/omarchy.
func UWSMEnvFile(omarchyPath string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by deomarchify - replaces the package-owned\n")
	fmt.Fprintf(&b, "# /usr/share/uwsm/env.d/10-omarchy after removing the omarchy-settings package.\n")
	fmt.Fprintf(&b, "# Changes require a session restart to take effect.\n\n")
	fmt.Fprintf(&b, "export OMARCHY_PATH=%q\n", omarchyPath)
	fmt.Fprintf(&b, "case \":$PATH:\" in\n")
	fmt.Fprintf(&b, "  *\":%s/bin:\"*) ;;\n", omarchyPath)
	fmt.Fprintf(&b, "  *) export PATH=\"%s/bin:$PATH\" ;;\n", omarchyPath)
	fmt.Fprintf(&b, "esac\n\n")
	fmt.Fprintf(&b, "export TERMINAL=xdg-terminal-exec\n")
	fmt.Fprintf(&b, "export EDITOR=\"omarchy-launch-editor --inline\"\n\n")
	fmt.Fprintf(&b, "command -v mise >/dev/null 2>&1 && eval \"$(mise activate bash --shims)\"\n")
	return b.String()
}

// BashrcOmarchyLine is the exact line this tool looks for and replaces in
// ~/.bashrc (originally hardcoding /usr/share/omarchy rather than using
// $OMARCHY_PATH, which is what makes it break on package removal).
const BashrcOmarchyLine = `[[ -r /usr/share/omarchy/default/bash/env-bootstrap ]] && source /usr/share/omarchy/default/bash/env-bootstrap`

// PatchBashrc replaces the hardcoded omarchy env-bootstrap source line with
// one pointing at the vendored checkout. Returns the patched content and
// whether a replacement was made (false means the line wasn't found, so the
// caller shouldn't silently assume success).
func PatchBashrc(original string, omarchyPath string) (patched string, changed bool) {
	replacement := fmt.Sprintf("[[ -r %s/default/bash/env-bootstrap ]] && source %s/default/bash/env-bootstrap", omarchyPath, omarchyPath)
	if !strings.Contains(original, BashrcOmarchyLine) {
		return original, false
	}
	return strings.Replace(original, BashrcOmarchyLine, replacement, 1), true
}

// ZshrcOmarchyPathPrefix is the line prefix this tool looks for in
// ~/.zshrc: `export OMARCHY_PATH=<anything>`.
const zshrcExportPrefix = "export OMARCHY_PATH="

// PatchZshrc rewrites the `export OMARCHY_PATH=...` line to point at the
// vendored checkout instead of ~/.local/share/omarchy.
func PatchZshrc(original string, omarchyPath string) (patched string, changed bool) {
	lines := strings.Split(original, "\n")
	found := false
	for i, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), zshrcExportPrefix) {
			lines[i] = fmt.Sprintf("export OMARCHY_PATH=%s", omarchyPath)
			found = true
		}
	}
	if !found {
		return original, false
	}
	return strings.Join(lines, "\n"), true
}
